// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFdqNG9eaXsYzc_YkDvKwfrk6Fjg6U0S0',
    appId: '1:904301111006:web:e7ed9e110c3ccc9947844f',
    messagingSenderId: '904301111006',
    projectId: 'sriway-6889f',
    authDomain: 'sriway-6889f.firebaseapp.com',
    storageBucket: 'sriway-6889f.firebasestorage.app',
    measurementId: 'G-FR4LZSMQK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnF2mjV-4h--wQaUiceqey6nRNz6g0GuI',
    appId: '1:904301111006:android:d949ed4b9f66ced947844f',
    messagingSenderId: '904301111006',
    projectId: 'sriway-6889f',
    storageBucket: 'sriway-6889f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYvnznStdnbrXg_c7QlgnawBjF9rBl5QE',
    appId: '1:904301111006:ios:add789fa66a993c347844f',
    messagingSenderId: '904301111006',
    projectId: 'sriway-6889f',
    storageBucket: 'sriway-6889f.firebasestorage.app',
    iosClientId: '904301111006-csbug3lhdvhq582fbofqqsmud47eqn0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.turathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYvnznStdnbrXg_c7QlgnawBjF9rBl5QE',
    appId: '1:904301111006:ios:add789fa66a993c347844f',
    messagingSenderId: '904301111006',
    projectId: 'sriway-6889f',
    storageBucket: 'sriway-6889f.firebasestorage.app',
    iosClientId: '904301111006-csbug3lhdvhq582fbofqqsmud47eqn0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.turathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFdqNG9eaXsYzc_YkDvKwfrk6Fjg6U0S0',
    appId: '1:904301111006:web:390d350f5da860e647844f',
    messagingSenderId: '904301111006',
    projectId: 'sriway-6889f',
    authDomain: 'sriway-6889f.firebaseapp.com',
    storageBucket: 'sriway-6889f.firebasestorage.app',
    measurementId: 'G-QH0TH417Y1',
  );

}